site_name: Антон Шиловский
site_url: https://shilovskyanton.ru/
theme:
  name: material
  language: ru
  font:
    text: Inter
    code: Fira Code
  palette:
    - scheme: slate
      primary: black
      accent: grey
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
extra_css:
  - styles/new_site.css?v=2
extra:
  features:
    - navigation.instant
nav:
 - Навигация:
      - Главная: index.md
      - Портфолио: portfolio.md
      - Контакты: contacts.md
extra_javascript:
  - js/modal.js
plugins:
  - glightbox
markdown_extensions:
  - toc:
      permalink: false
  - admonition
  - footnotes
  - attr_list
  - pymdownx.superfences
  - pymdownx.emoji
  - md_in_html
